//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billetera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Billetera()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Id_Billetera { get; set; }
        public Nullable<decimal> Total_Disponible { get; set; }
        public Nullable<decimal> Total_Canjeadas { get; set; }
        public Nullable<decimal> Total_Generada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
