//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentroAcopio
    {
        public int Id_Centro { get; set; }
        public string nombre { get; set; }
        public string direccionExacta { get; set; }
        public string Id_Usuario { get; set; }
        public Nullable<int> Id_Provincia { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual Provincia Provincia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
