//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detall_Factura
    {
        public int Id_detall { get; set; }
        public Nullable<int> Id_Enca { get; set; }
        public Nullable<int> Id_Material { get; set; }
        public Nullable<int> Id_Cupon { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    
        public virtual Enca_Factura Enca_Factura { get; set; }
        public virtual Material Material { get; set; }
    }
}
