//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enca_Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enca_Factura()
        {
            this.Detall_Factura = new HashSet<Detall_Factura>();
        }
    
        public int Id_Enca { get; set; }
        public string Id_Usuario { get; set; }
        public Nullable<int> Id_Centro { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual CentroAcopio CentroAcopio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detall_Factura> Detall_Factura { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
